### ISSUE TITLE
Rename package to @espresso-org/...

### ISSUE THREAD

**Issue by macor161** [espresso-org/aragon-drive#22]
We have a new npm organization: www.npmjs.com/org/espresso-org
For the sake of uniformity, we should standardize our package names around this organization.
Here are some propositions for the Drive App, feel free to add your own:

- @espresso-org/aragon-drive
- @espresso-org/aragon-drive-app
- @espresso-org/drive
- @espresso-org/drive-app
- something else?

**Comment by juslar** [comment]
I think I prefer @espresso-org/aragon-drive!

**Comment by juslar** [comment]
So let's settle on @espresso-org/aragon-drive.

**Comment by juslar** [comment]
Done.
