### ISSUE TITLE
App must be refreshed after a settings modification

### ISSUE THREAD

**Issue by macor161** [espresso-org/aragon-drive#27]
After the user changes the settings, the app does not use the new configuration, the page must be refresh.
The new settings should be used automatically without any refresh.

**Comment by juslar** [comment]
The bug only seems to be happening when I try to add a file with a wrong configuration and then set a correct configuration and try to upload the same file without refreshing the app. Weird.

**Comment by juslar** [comment]
Finally, the bug was due to the onChange event not being triggered when uploading the same file twice. It didn't have anything to do with the configuration :)

**Comment by macor161** [comment]
Fixed
